//
//  KPHGeneratePasswordHandler.m
//  keepasshttp-objc
//
//  Created by Tim Kretschmer on 4/5/14.
//  Copyright (c) 2014 xbigtk13x. All rights reserved.
//

#import "KPHGeneratePasswordHandler.h"

@implementation KPHGeneratePasswordHandler
- (void) handle: (Request*)request response:(Response*)response aes:(Aes*)aes
{
    byte[] pbEntropy = null;
    ProtectedString psNew;
    PwProfile autoProfile = Program.Config.PasswordGenerator.AutoGeneratedPasswordsProfile;
    PwGenerator.Generate(out psNew, autoProfile, pbEntropy, Program.PwGeneratorPool);
    
    byte[] pbNew = psNew.ReadUtf8();
    if (pbNew != null)
    {
        uint uBits = QualityEstimation.EstimatePasswordBits(pbNew);
        ResponseEntry item = new ResponseEntry(Request.GENERATE_PASSWORD, uBits.ToString(), StrUtil.Utf8.GetString(pbNew), Request.GENERATE_PASSWORD, null);
        resp.Entries.Add(item);
        resp.Success = true;
        resp.Count = 1;
        MemUtil.ZeroByteArray(pbNew);
    }
    
    resp.Id = request.Id;
    [KPHProtocol SetResponseVerifier:response aes:aes];
    [KPHProtocol encryptResponse:response aes:aes];
}
@end
